KSEIWebKtp/Controllers/InquiryController.cs
using KSEIWebKtp.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ReflectionIT.Mvc.Paging;
using System.Linq;
using System.Threading.Tasks;

namespace KSEIWebKtp.Controllers
{
    [Authorize]
    public class InquiryController : Controller
    {
        private readonly Models.KseiContext _context;

        public InquiryController(Models.KseiContext context)
        {
            _context = context;
        }

        // GET: /<controller>/
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> All(int page = 1)
        {
            var dataktp =
                    from d in _context.Dataktp
                    join ju in _context.Upload on d.Upload_ID equals ju.ID into bp
                    from c in bp.DefaultIfEmpty()
                    select new InquiryViewModel
                    {
                        NIK = d.NIK,
                        Nama = d.Nama,
                        Tgl_Upload = c.Tgl_Upload,
                        User_ID = c.User_ID,
                        File_Upload = c.File_Upload,
                        Tempat_lahir = d.Tempat_lahir,
                        Tanggal_lahir = d.Tanggal_lahir,
                        Jk = d.Jk,
                        Alamat = d.Alamat,
                        RtRw = d.RtRw,
                        KelDesa = d.KelDesa,
                        Kecamatan = d.Kecamatan,
                        Agama = d.Agama,
                        Status = d.Status,
                        Pekerjaan = d.Pekerjaan,
                        Kewarganegaraan = d.Kewarganegaraan,
                        Berlaku = d.Berlaku,
                        Provinsi = d.Provinsi,
                        ID = c.ID
                    };

            var qry = dataktp.OrderByDescending(p => p.Tgl_Upload);
            var model = await PagingList<KSEIWebKtp.ViewModel.InquiryViewModel>.CreateAsync(qry, 20, page);
            model.Action = "All";
            return View(model);
        }

        [HttpPost]
        public IActionResult Filter(InquiryViewModel ivm)
        {
            if (ModelState.IsValid)
            {
                var dataktp =
                    from d in _context.Dataktp
                    join ju in _context.Upload on d.Upload_ID equals ju.ID into bp
                    from c in bp.DefaultIfEmpty()
                    where c.Tgl_Upload >= ivm.Tgl_Upload && c.Tgl_Upload <= ivm.Sd_upload  
                    orderby c.Tgl_Upload descending
                    select new InquiryViewModel
                    {
                        NIK = d.NIK, Nama = d.Nama, Tgl_Upload = c.Tgl_Upload, User_ID = c.User_ID, File_Upload = c.File_Upload,
                        Tempat_lahir = d.Tempat_lahir, Tanggal_lahir = d.Tanggal_lahir, Jk = d.Jk, Alamat = d.Alamat, RtRw = d.RtRw,
                        KelDesa = d.KelDesa, Kecamatan = d.Kecamatan, Agama = d.Agama, Status = d.Status, Pekerjaan = d.Pekerjaan,
                        Kewarganegaraan = d.Kewarganegaraan, Berlaku = d.Berlaku, Provinsi = d.Provinsi, ID = c.ID
                    };

                if (ivm.NIK != null)
                {
                    dataktp = dataktp.Where(d => d.NIK.Contains(ivm.NIK));
                }
                if (ivm.Nama != null)
                {
                    dataktp = dataktp.Where(d => d.Nama.Contains(ivm.Nama));
                }

                if (dataktp != null)
                {
                    return View(dataktp.ToList());
                }
                else
                {
                    ViewBag.msg = "Data Tidak ditemukan !";
                    return View();
                }
            }

            return View("Index",ivm);            
        }
    }

}

KSEIWebKtp/Controllers/PemadananController.cs
using KSEIWebKtp.Models;
using KSEIWebKtp.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using OfficeOpenXml;
using ReflectionIT.Mvc.Paging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace KSEIWebKtp.Controllers
{
    [Authorize]
    public class PemadananController : Controller
    {
        private readonly KseiContext _context;
        private UserManager<ApplicationUser> _userManager;
        private IHostingEnvironment _environment;

        public PemadananController(KseiContext context, UserManager<ApplicationUser> userManager, IHostingEnvironment environment)
        {
            _context = context;
            _userManager = userManager;
            _environment = environment;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index(string filter, int page = 1, string sortExpression = "Tgl_Upload")
        {
            ViewData["asdf"] = "asdf";
            var dataktp =
                    from d in _context.Dataktp
                    join ju in _context.Upload on d.Upload_ID equals ju.ID into bp
                    from c in bp.DefaultIfEmpty()
                    select new InquiryViewModel
                    {
                        NIK = d.NIK,
                        Nama = d.Nama,
                        Tgl_Upload = c.Tgl_Upload,
                        User_ID = c.User_ID,
                        File_Upload = c.File_Upload,
                        Tempat_lahir = d.Tempat_lahir,
                        Tanggal_lahir = d.Tanggal_lahir,
                        Jk = d.Jk,
                        Alamat = d.Alamat,
                        RtRw = d.RtRw,
                        KelDesa = d.KelDesa,
                        Kecamatan = d.Kecamatan,
                        Agama = d.Agama,
                        Status = d.Status,
                        Pekerjaan = d.Pekerjaan,
                        Kewarganegaraan = d.Kewarganegaraan,
                        Berlaku = d.Berlaku,
                        Provinsi = d.Provinsi,
                        Tgl_Baca = d.Tgl_Baca,
                        ID = c.ID
                    };

            if (!string.IsNullOrWhiteSpace(filter))
            {
                dataktp = dataktp.Where(p => p.NIK.Contains(filter) || p.Nama.Contains(filter) || p.User_ID.Contains(filter)
                || p.Alamat.Contains(filter) || p.Tempat_lahir.Contains(filter) || p.Tanggal_lahir.Contains(filter)
                || p.Kecamatan.Contains(filter) || p.KelDesa.Contains(filter) || p.Pekerjaan.Contains(filter)
                || p.Provinsi.Contains(filter));
            }

            var qry = dataktp.OrderByDescending(p => p.Tgl_Upload);
            var model = await PagingList<InquiryViewModel>.CreateAsync(qry, 20, page, sortExpression, "Tgl_Upload");
            model.Action = "Index";
            model.RouteValue = new RouteValueDictionary {
                { "filter", filter}
            };
            return View(model);
        }

        public IActionResult Filter()
        {
            var dari = HttpContext.Request.Form["dari"];
            dari += " 00:00:00";
            var sampai = HttpContext.Request.Form["sampai"];
            sampai += " 23:59:59";
            var dataktp =
                    from d in _context.Dataktp
                    join ju in _context.Upload on d.Upload_ID equals ju.ID into bp
                    from c in bp.DefaultIfEmpty()
                    //where c.Tgl_Upload >= Convert.ToDateTime(dari) && c.Tgl_Upload <= Convert.ToDateTime(sampai)
                    orderby c.Tgl_Upload descending
                    select new InquiryViewModel
                    {
                        NIK = d.NIK,
                        Nama = d.Nama,
                        Tgl_Upload = c.Tgl_Upload,
                        User_ID = c.User_ID,
                        File_Upload = c.File_Upload,
                        Tempat_lahir = d.Tempat_lahir,
                        Tanggal_lahir = d.Tanggal_lahir,
                        Jk = d.Jk,
                        Alamat = d.Alamat,
                        RtRw = d.RtRw,
                        KelDesa = d.KelDesa,
                        Kecamatan = d.Kecamatan,
                        Agama = d.Agama,
                        Status = d.Status,
                        Pekerjaan = d.Pekerjaan,
                        Kewarganegaraan = d.Kewarganegaraan,
                        Berlaku = d.Berlaku,
                        Provinsi = d.Provinsi,
                        Tgl_Baca = d.Tgl_Baca,
                        ID = c.ID
                    };
            dataktp = dataktp.Where(p => (p.Tgl_Upload >= Convert.ToDateTime(dari) && p.Tgl_Upload <= Convert.ToDateTime(sampai)) || (p.Tgl_Baca >= Convert.ToDateTime(dari) && p.Tgl_Baca <= Convert.ToDateTime(sampai)));
            //dataktp = dataktp.Where(p => p.Tgl_Upload >= Convert.ToDateTime(dari) && p.Tgl_Upload <= Convert.ToDateTime(sampai));
            //dataktp = dataktp.OrderByDescending(p => p.Tgl_Upload);            
            return View(dataktp);
        }

        [HttpPost]
        public async Task<IActionResult> Cek()
        {
            var pilih = HttpContext.Request.Form["Pilih"].ToArray();
            var user = await _userManager.GetUserAsync(User);
            var ip_address = user.IP_ADDRESS_WS;
            var password = user.PASSWORD_WS;
            var user_id = user.USER_WS;
            var client = new HttpClient();
            List<PemadananViewModel> listValue = new List<PemadananViewModel>();

            foreach (var id in pilih)
            {
                var did = Convert.ToInt32(id);
                var dataktp = await _context.Dataktp
                                .SingleOrDefaultAsync(m => m.ID == did);
                var nik = dataktp.NIK;
                var upload = await _context.Upload
                                .SingleOrDefaultAsync(m => m.ID == dataktp.Upload_ID);
                try
                {
                    string json = "{\"NIK\": \"" + nik + "\"," +
                                         "\"ip_address\": \"" + ip_address + "\"," +
                                          "\"password\": \"" + password + "\"," +
                                          "\"user_id\": \"" + user_id + "\"}";
                    var js = await client.PostAsync(new Uri("http://172.16.160.25:8000/dukcapil/get_json/KSEI/CALL_NIK"), new StringContent(json, Encoding.UTF8, "application/json"));
                    //var js = await client.PostAsync(new Uri("http://localhost/ksei"), new StringContent(json, Encoding.UTF8, "application/json"));
                    var result = await js.Content.ReadAsStringAsync();
                    if (result != null)
                    {
                        Webservice dt = JsonConvert.DeserializeObject<Webservice>(result);                        
                        if (dt.content[0].RESPON != null)
                        {
                            var dtk = new PemadananViewModel
                            {
                                File_Upload = upload.File_Upload,
                                Tgl_Upload = upload.Tgl_Upload,
                                User_ID = upload.User_ID,
                                dtws = null,
                                idktp = dataktp.ID,
                                dtktp = dataktp,
                                idupload = upload.ID,
                                idws = 0
                            };
                            listValue.Add(dtk);
                        }
                        else
                        {
                            var ws = new Webservice
                            {
                                PETUGAS_CEK = user_id,
                                TGL_CEK = DateTime.Now
                            };

                            _context.Webservice.Add(ws);
                            await _context.SaveChangesAsync();
                            var iddtws = ws.ID;

                            Kontenws dbws = dt.content[0];
                            dbws.WebserviceID = iddtws;
                            _context.Kontenws.Add(dbws);
                            await _context.SaveChangesAsync();

                            var dtws = new Dataktp
                            {
                                NIK = dt.content[0].NIK,
                                Nama = dt.content[0].NAMA_LGKP,
                                Alamat = dt.content[0].ALAMAT,
                                Agama = dt.content[0].AGAMA,
                                RtRw = dt.content[0].NO_RT + "/" + dt.content[0].NO_RW,
                                KelDesa = dt.content[0].KEL_NAME,
                                Kecamatan = dt.content[0].KEC_NAME,
                                Status = dt.content[0].STATUS_KAWIN,
                                Pekerjaan = dt.content[0].JENIS_PKRJN,
                                Tempat_lahir = dt.content[0].TMPT_LHR,
                                Tanggal_lahir = dt.content[0].TGL_LHR,
                                Jk = dt.content[0].JENIS_KLMIN,
                                Goldarah = dt.content[0].GOL_DARAH,
                                Provinsi = dt.content[0].PROP_NAME
                            };
                            var dtk = new PemadananViewModel
                            {
                                File_Upload = upload.File_Upload,
                                Tgl_Upload = upload.Tgl_Upload,

KSEIWebKtp/Views/Shared/_Layout.cshtml
@using System.Security.Claims 
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="author" name="Fauzan Azmi" />
    <meta content="author contact" name="http://www.azmifauzan.net" />
    <title>@ViewData["Title"] - KSEI</title>

    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" style="margin-top:8px; margin-right:20px;" width="90px" alt="KSEI" class="img-responsive" /></a>
</div>
            <div class="navbar-collapse collapse">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Upload" asp-action="Index">Upload</a></li>
                        <li><a asp-area="" asp-controller="Inquiry" asp-action="Index">Inquiry</a></li>
                        <li><a class="dropdown dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Web Service <span class="caret"></span></a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li><a asp-area="" asp-controller="Webservice" asp-action="Index">Cek Web Service</a></li>
                                <li><a asp-area="" asp-controller="Pemadanan" asp-action="Index">Pemadanan</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a asp-area="" asp-controller="Webservice" asp-action="Config">Konfigurasi</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a asp-area="" asp-controller="Login" asp-action="Out">Log Out</a></li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li><a asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
                    </ul>
                }
            </div>
        </div>
    </nav>
    <div class="container body-content" style="margin-top:30px;">
        @RenderBody()
        <br/><br/><br/><hr />
        <footer>
            <p class="text-center">Copyright &copy; 2017 - PT. Kustodian Sentral Efek Indonesia</p>
        </footer>
    </div>    

    <environment names="Development,Staging,Production">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-ui/jquery-ui.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
    <script type="text/javascript">
        $(function () {
            $("#datepicker").datepicker({ dateFormat: 'yy/mm/dd' });
            $("#datepicker2").datepicker({ dateFormat: 'yy/mm/dd' });
        });

        function cekall() {
            var aa = document.getElementsByTagName("input");
            for (var i = 0; i < aa.length; i++) {
                if (aa[i].type == 'checkbox') {
                    if (aa[i].checked == true) {
                        aa[i].checked = false;
                    }
                    else {
                        aa[i].checked = true;
                    }
                }
            }
        }
    </script>
</body>
</html>